# Configuración de Gitleaks

# Título para el informe (opcional)
# title = "Informe de Gitleaks"

# [rules]
# Aquí puedes definir reglas personalizadas si es necesario.
# Por defecto, Gitleaks usa un conjunto predefinido de reglas.

[allowlist]
# Permite ignorar commits específicos
# commits = [
#   "abcdef1234567890", # Ejemplo de hash de commit
# ]

# Permite ignorar archivos específicos por ruta
# paths = [
#   '''secrets/config.yaml''', # Ejemplo de ruta de archivo
#   '''pkg/test_data/''',     # Ejemplo de directorio
# ]

# Permite ignorar secretos específicos por su valor (expresión regular)
# regexps = [
#   '''AKIAIOSFODNN7EXAMPLE''', # Ejemplo de clave de AWS falsa
# ]

# Permite ignorar secretos basados en descripciones de reglas
# description = [
#   '''Generic API Key''', # Ejemplo de descripción de regla
# ]
