name: gitleaks
on: [push, pull_request]
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para que Gitleaks escanee todo el historial
      - uses: gitleaks/gitleaks-action@v2
        env:
          # Opcional: Ruta al archivo de configuración de Gitleaks
          # GITLEAKS_CONFIG: .gitleaks.toml 
          # Necesario para reportar el estado a GitHub si el repositorio es privado
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
